[project]
name = "system-design-12-algos"
version = "0.1.0"
description = "algorithms that are sometimes used in systems here and there"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "jupyterlab>=4.3.5",
]
